In [1]:
import numpy as np

In [3]:
# Example/Code:
# Python list
python_list = [1, 2, 3, 4, 5]
# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

# Performing a numerical operation (multiply each element by 2)
# Using Python list
python_list_times_two = [x * 2 for x in python_list]
# Using NumPy array
numpy_array_times_two = numpy_array * 2

print("Python List (times two):", python_list_times_two)
print("NumPy Array (times two):", numpy_array_times_two)


Python List (times two): [2, 4, 6, 8, 10]
NumPy Array (times two): [ 2  4  6  8 10]


In [7]:
import numpy as np

In [19]:
'''3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

# code
arr1=np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
shape=arr1.shape
size=arr1.size
dimension=arr1.ndim

print("arr1: ",arr1)
print("Shape of the Given arr1: ",shape)
print("Size of the Given arr1: ",size)
print("Dimensions of the Given arr1: ",dimension)

arr1:  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape of the Given arr1:  (1, 3, 4)
Size of the Given arr1:  12
Dimensions of the Given arr1:  3


In [34]:
'''4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

#code
arr=np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
first_row=arr[0,0]
print(" Given array: ",arr)
print("first row: ", first_row)

 Given array:  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
first row:  [1 2 3 4]


In [50]:
'''5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

# code
arr=np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
index=arr[0,2,3]
print("The element at the third row and fourth column is : ",index)

The element at the third row and fourth column is :  12


In [2]:
'''6. Write code to extract all odd-innexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

# code
import numpy as np
# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract odd-indexed elements
odd_indexed_elements = [element for row in arr for index, element in enumerate(row) if index % 2 != 0]

# Convert the result to NumPy array
result_array = np.array(odd_indexed_elements)

print(result_array)


[ 2  4  6  8 10 12]


In [3]:
'''7. How can you generate a random 3x3 matrix with values between 0 and 1?'''

# code
import numpy as np
# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.07630586 0.57505657 0.48408574]
 [0.26188357 0.38211872 0.78396341]
 [0.54413637 0.94072918 0.38221803]]


In [5]:
'''8. Describe the difference between np.random.rand and np.random.randn?'''

# Ans
'''
The functions np.random.rand and np.random.randn in the NumPy library are both used for generating random numbers, 
but they have some key differences in terms of the distribution of the generated values.

np.random.rand:

Generates random values from a uniform distribution over the interval [0, 1).
The generated values are floats and are uniformly distributed.
You can specify the shape of the output array by passing the dimensions as arguments. 
For example, np.random.rand(2, 3) will create a 2x3 array.
'''

# code for np.random.rand:
import numpy as np
# Example of np.random.rand
random_values_uniform = np.random.rand(2, 3)


'''
np.random.randn:

Generates random values from a standard normal distribution (mean=0, standard deviation=1).
The generated values are floats and are normally distributed.
You can also specify the shape of the output array in the same way as np.random.rand.
'''
# code for np.random.randn
import numpy as np

# Example of np.random.randn
random_values_normal = np.random.randn(2, 3)

In [6]:
'''9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

# code
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase dimension along axis 0 (add a new axis at the beginning)
new_dimension_array = original_array[np.newaxis, :, :]

# Alternatively, you can use np.expand_dims
# new_dimension_array = np.expand_dims(original_array, axis=0)

print("Original Array:")
print(original_array)

print("\nArray with Increased Dimension:")
print(new_dimension_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [7]:
'''10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

# code
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose using numpy.transpose
transposed_array = np.transpose(original_array)

# Alternatively, you can use the .T attribute
# transposed_array = original_array.T

print("Original Array:")
print(original_array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [9]:
'''11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1. Index wise multiplication
2. Matix multiplication
3.Add both the matix
4. Subtact matix B from A 
5. Diide Matix B by A
'''

# Code

# Matrix A2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Matrix B2
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Display Matrix A2
print("Matrix A2:")
print(A2)

# Display Matrix B2
print("\nMatrix B2:")
print(B2)


#1. Index wise multiplication
index_wise_multiplication = A2 * B2
print("1. Index-wise Multiplication:")
print(index_wise_multiplication)

#2. Matix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # B2.T is the transpose of B2
print("\n2. Matrix Multiplication:")
print(matrix_multiplication)

# 3.Add both the matix
matrix_sum = A2 + B2
print("\n3. Matrix Sum:")
print(matrix_sum)

# 4. Subtact matix B from A 
matrix_difference = A2 - B2
print("\n4. Matrix Difference (A - B):")
print(matrix_difference)

#5. Diide Matix B by A
matrix_division = np.divide(B2, A2)
print("\n5. Matrix Division (B / A):")
print(matrix_division)


Matrix A2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1. Index-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix Sum:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix Difference (A - B):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix Division (B / A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
'''12. Which function in Numpy can be used to swap the byte order of an array?'''

# Ans
'''
In NumPy, you can use the byteswap function to swap the byte order of an array.
The byteswap function swaps the byte order of the elements of an array in place
'''
# code
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
swapped_array = original_array.byteswap()

print("Original Array:")
print(original_array)

print("\nSwapped Array:")
print(swapped_array)


Original Array:
[1 2 3 4]

Swapped Array:
[16777216 33554432 50331648 67108864]


In [11]:
'''13. What is the significance of the np.linalg.inv function?'''

#Ans
'''
The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. 
The inverse of a matrix is a matrix that, when multiplied with the original matrix, yields the identity matrix.

Numerical Stability:

In some cases, solving a system of linear equations using matrix inversion can be more numerically stable than direct 
methods. However, it's essential to be cautious with matrix inversion in the presence of numerical instability, 
especially for matrices that are ill-conditioned or nearly singular.

Applications in Statistics and Optimization:

In statistics and optimization problems, matrix inversion is often used in techniques such as linear regression, 
where finding the coefficients involves solving a system of linear equations.
'''

# code
import numpy as np

# Coefficient matrix A
A = np.array([[2, 1],
              [3, 4]])

# Right-hand side vector B
B = np.array([1, 2])

# Solve for X in AX = B
X = np.linalg.inv(A).dot(B)

print("Solution vector X:")
print(X)


Solution vector X:
[0.4 0.2]


In [12]:
'''14. What does the np.reshape function do, and how is it used?'''

# Ans
'''
The np.reshape function in NumPy is used to change the shape of an array without changing its data. 
It allows you to reorganize the elements of an array to a new shape while maintaining the same data.

The total number of elements in the original array must be equal to the total number of elements in the reshaped array.
The reshaping is done in a row-major ('C') order by default, but you can specify 'F' for column-major order if needed.
If one of the dimensions in the new shape is specified as -1,
NumPy automatically calculates the size of that dimension based on the size of the original array.
'''

# code
import numpy as np

# Create a 1D array with 12 elements
original_array = np.arange(12)

# Reshape the 1D array to a 3x4 matrix
reshaped_array = np.reshape(original_array, (3, 4))

print("Original Array (1D):")
print(original_array)

print("\nReshaped Array (3x4 matrix):")
print(reshaped_array)


Original Array (1D):
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (3x4 matrix):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
'''15. What is broadcasting in Numpy?'''

# ans
'''
Broadcasting in NumPy is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes 
and sizes, often eliminating the need for explicit loops and making the code more concise and efficient. 
The term "broadcasting" refers to the ability of NumPy to automatically and intelligently extend or broadcast dimensions 
of arrays to perform element-wise operations.

The key concept behind broadcasting is that when operating on arrays of different shapes, NumPy automatically adjusts
the shape of the smaller array so that they can be combined element-wise. The smaller array is "broadcast" over the 
larger array to make their shapes compatible.

The broadcasting rules are as follows:

If the arrays do not have the same rank (number of dimensions), pad the smaller array's shape with ones on its left side.
Compare the sizes of corresponding dimensions:
If the sizes are equal, the dimensions are compatible.
If one of the sizes is 1, the dimensions are compatible, and the array with size 1 will be broadcast to match the other
array's size in that dimension.
If the sizes are neither equal nor 1, the arrays are incompatible, and broadcasting will result in an error.
'''

# Code
import numpy as np

# Example arrays
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

# Broadcasting: B is broadcasted to each row of A
result = A + B

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nResult after Broadcasting (A + B):")
print(result)


Array A:
[[1 2 3]
 [4 5 6]]

Array B:
[10 20 30]

Result after Broadcasting (A + B):
[[11 22 33]
 [14 25 36]]
